#[cfg(test)]
mod tests {
    use crate::core::bits::{Blade, Sector};
    use crate::core::compute::multivector::{add_mv, scale_mv};
    use crate::core::ir::Multivector;
    use crate::state::ideal::IdealState;

    const EPS: f64 = 1e-10;

    fn approx_eq(a: f64, b: f64) -> bool {
        (a - b).abs() < EPS
    }

    fn has_term(
        mv: &Multivector,
        left: Option<Sector>,
        blade: Blade,
        right: Option<Sector>,
        coeff: f64,
    ) -> bool {
        mv.terms.iter().any(|t| {
            t.left == left
                && t.blade == blade
                && t.right == right
                && approx_eq(t.coeff, coeff)
        })
    }

    #[test]
    fn materialize_identity_on_vacuum_returns_vacuum() {
        // The simplest ideal state is just:
        //
        //   ψ = 1 · P
        //
        // so materialization should return P itself.
        let p = Sector::from_bits(0, 1);

        let st = IdealState::new(Multivector::from_blade(1, Blade::identity(), 1.0), p);
        let psi = st.materialize();

        assert_eq!(psi.terms.len(), 1);
        assert!(has_term(&psi, None, Blade::identity(), Some(p), 1.0));
    }

    #[test]
    fn x_on_vacuum_flips_the_sector() {
        // Algebraically:
        //
        //   e2 P = Q e2
        //
        // so the ideal state generated by X acting on the vacuum should
        // land in the Q sector.
        let p = Sector::from_bits(0, 1);
        let q = Sector::from_bits(1, 1);

        let st = IdealState::new(Multivector::from_blade(1, Blade::x(0), 1.0), p);
        let psi = st.materialize();

        assert_eq!(psi.terms.len(), 1);
        assert!(has_term(&psi, None, Blade::x(0), Some(q), 1.0));
    }

    #[test]
    fn one_and_e1_represent_the_same_single_qubit_state() {
        // In the quotient picture:
        //
        //   [1] = [e1]
        //
        // because
        //
        //   1·P = P
        //   e1·P = P
        //
        // So these are different representatives of the same physical state.
        let p = Sector::from_bits(0, 1);

        let a = IdealState::new(Multivector::from_blade(1, Blade::identity(), 1.0), p);
        let b = IdealState::new(Multivector::from_blade(1, Blade::z(0), 1.0), p);

        assert!(a.physically_eq(&b));
    }

    #[test]
    fn annihilator_gauge_shift_does_not_change_the_state() {
        // Single-qubit annihilator contains Q and e2 Q.
        //
        // So if B is in the annihilator, then:
        //
        //   (A + B)P = AP
        //
        // We test the displayed example:
        //
        //   1 ~ 1 + Q
        //
        // because QP = 0.
        let p = Sector::from_bits(0, 1);

        let one = Multivector::from_blade(1, Blade::identity(), 1.0);
        let z = Multivector::from_blade(1, Blade::z(0), 1.0);

        // Q = (I - Z)/2
        let q = scale_mv(&add_mv(&one, &scale_mv(&z, -1.0)), 0.5);

        let s1 = IdealState::new(one.clone(), p);
        let s2 = IdealState::new(add_mv(&one, &q), p);

        assert!(s1.physically_eq(&s2));
    }

    #[test]
    fn left_apply_updates_only_the_representative() {
        // For ideal states:
        //
        //   U · (A P) = (U A) P
        //
        // so left application should only change the representative,
        // not the vacuum sector.
        let p = Sector::from_bits(0, 1);

        let st = IdealState::new(Multivector::from_blade(1, Blade::identity(), 1.0), p);
        let out = st.left_apply(&Multivector::from_blade(1, Blade::x(0), 1.0));

        assert_eq!(out.vacuum, p);

        let psi = out.materialize();
        let q = Sector::from_bits(1, 1);

        assert!(has_term(&psi, None, Blade::x(0), Some(q), 1.0));
    }

    #[test]
    fn lift_is_representative_side_not_materialized_state() {
        // The MVP lift currently returns a simplified representative,
        // not the materialized ideal element.
        //
        // So for X acting on the vacuum:
        //
        //   lift() = X
        //   materialize() = X P = Q X
        let p = Sector::from_bits(0, 1);

        let st = IdealState::new(Multivector::from_blade(1, Blade::x(0), 1.0), p);

        let rep = st.lift();
        let psi = st.materialize();

        // Representative is still plain X with no explicit sector attached.
        assert!(rep.terms.iter().any(|t| {
            t.left.is_none()
                && t.right.is_none()
                && t.blade == Blade::x(0)
                && approx_eq(t.coeff, 1.0)
        }));

        // Materialized ideal element should carry the vacuum projection.
        assert_ne!(rep, psi);
    }
}