use core::fmt;

/// A packed discrete right rotor generated by local bivectors J_i = e₁ ∧ e₂.
/// Each qubit can be in one of 8 classes (0..7) corresponding to multiples of π/4 rotations.

/// A rotor in Clifford algebra is built from exponentials of bivectors.
/// Locally on each qubit, we have:
///
/// - J_i = e₁ ∧ e₂ (local bivector, J² = -1)
/// - exp((θ/2) J_i) for θ ∈ {0, π/2, π, 3π/2, ...}
///
/// Quarter-turn units (QTU) of π/4 give us:
/// ```
/// k=0: exp(0)           = I           (identity)
/// k=1: exp((π/4) J_i)   = cos(π/8) + J_i sin(π/8)
/// k=2: exp((π/2) J_i)   = J_i         (90° rotation)
/// k=3: exp((3π/4) J_i)  = cos(3π/8) + J_i sin(3π/8)
/// k=4: exp(π J_i)       = -I          (180° rotation)
/// k=5: exp((5π/4) J_i)  = -exp((π/4) J_i)
/// k=6: exp((3π/2) J_i)  = -J_i
/// k=7: exp((7π/4) J_i)  = -exp((3π/4) J_i)
/// ```
///
/// The key insight: classes 4..7 are always canonicalized as
/// (class mod 4) with a global ±1 sign, reducing storage to two quaternary qubits per position.
///
/// # Packed Representation
///
/// Instead of storing [local_class_i for i in 0..n], we distribute information
/// across three masks:
///
/// - **q1_mask**: Which qubits have class ≡ 1 (mod 4)
/// - **q2_mask**: Which qubits have class ≡ 2 (mod 4)
/// - **q3_mask**: Which qubits have class ≡ 3 (mod 4)
/// - **sign**: Global ± factor
///
/// (Class 0 is implicit: qubit i has class 0 iff all three masks have bit i = 0.)
///
/// # Use Cases
///
/// This representation is optimized for:
/// 1. **S and T gates**: Stored as class-2 and class-1 rotors
/// 2. **Y-style biactions**: Conjugation by local bivectors
/// 3. **Rotor composition**: Via local class arithmetic (modulo the sign bit)
/// 4. **GPU compatibility**: Bitwise masks are naturally parallel
/// 5. **Hashability**: Fixed 32-byte footprint, power-of-2 alignment
///
/// # Example
///
/// ```
/// let t_at_0 = Rotor::t_at(0);  // T gate on qubit 0 = class 1
/// assert_eq!(t_at_0.q1_mask, 1);
/// assert_eq!(t_at_0.q2_mask, 0);
/// assert_eq!(t_at_0.q3_mask, 0);
/// assert!(!t_at_0.sign);
///
/// let s_at_1 = Rotor::s_at(1);  // S gate on qubit 1 = class 2
/// assert_eq!(s_at_1.q2_mask, 2);
/// ```
///
/// # Memory Layout
///
/// ```text
/// ┌──────────────┬──────────────┬──────────────┬──────┐
/// │   q1_mask    │   q2_mask    │   q3_mask    │ sign │  (25 bytes total, padded)
/// │  (8 bytes)   │  (8 bytes)   │  (8 bytes)   │ (1b) │
/// └──────────────┴──────────────┴──────────────┴──────┘
/// ```
#[derive(Clone, Copy, Default, PartialEq, Eq, Hash)]
#[repr(C)]
pub struct Rotor {
    /// Bitmask: qubit i has local class 1 iff bit i = 1.
    pub q1_mask: u64,
    /// Bitmask: qubit i has local class 2 iff bit i = 1.
    pub q2_mask: u64,
    /// Bitmask: qubit i has local class 3 iff bit i = 1.
    pub q3_mask: u64,

    /// Global sign: true = negative, false = positive.
    pub sign: bool,
}

impl fmt::Debug for Rotor {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = if self.sign { "-" } else { "+" };
        f.debug_struct("Rotor")
            .field("sign", &s)
            .field("q1_mask", &format_args!("{:#066b}", self.q1_mask))
            .field("q2_mask", &format_args!("{:#066b}", self.q2_mask))
            .field("q3_mask", &format_args!("{:#066b}", self.q3_mask))
            .finish()
    }
}

// ============================================================================
// CONSTRUCTORS & IDENTITY
// ============================================================================

impl Rotor {
    /// Create a rotor from explicit class masks and sign.
    #[inline(always)]
    pub const fn new(q1_mask: u64, q2_mask: u64, q3_mask: u64, sign: bool) -> Self {
        Self {
            q1_mask,
            q2_mask,
            q3_mask,
            sign,
        }
    }

    /// The multiplicative identity rotor (all zeros, positive sign).
    #[inline(always)]
    pub const fn identity() -> Self {
        Self {
            q1_mask: 0,
            q2_mask: 0,
            q3_mask: 0,
            sign: false,
        }
    }

    /// Check if this rotor is the multiplicative identity.
    #[inline(always)]
    pub const fn is_identity(self) -> bool {
        self.q1_mask == 0 && self.q2_mask == 0 && self.q3_mask == 0 && !self.sign
    }

    /// Negate this rotor (multiply by -1).
    #[inline(always)]
    pub const fn negate(self) -> Self {
        Self {
            q1_mask: self.q1_mask,
            q2_mask: self.q2_mask,
            q3_mask: self.q3_mask,
            sign: !self.sign,
        }
    }

    /// Return an unsigned copy of this rotor (discarding the sign bit).
    ///
    /// Useful for extracting just the local class information.
    #[inline(always)]
    pub const fn unsigned(self) -> Self {
        Self {
            q1_mask: self.q1_mask,
            q2_mask: self.q2_mask,
            q3_mask: self.q3_mask,
            sign: false,
        }
    }
}

// ============================================================================
// SINGLE-QUBIT CONSTRUCTORS
// ============================================================================

impl Rotor {
    /// Local quarter-turn rotor at qubit i: exp((π/4) J_i).
    ///
    /// Also called the T gate: T = S^(1/2).
    #[inline(always)]
    pub const fn quarter_turn_at(i: usize) -> Self {
        Self {
            q1_mask: 1u64 << i,
            q2_mask: 0,
            q3_mask: 0,
            sign: false,
        }
    }

    /// Local 90° rotor at qubit i: J_i = exp((π/2) J_i).
    ///
    /// J_i² = -I (local). This is half of the S gate when properly composed.
    #[inline(always)]
    pub const fn j_at(i: usize) -> Self {
        Self {
            q1_mask: 0,
            q2_mask: 1u64 << i,
            q3_mask: 0,
            sign: false,
        }
    }

    /// Local three-quarter-turn rotor at qubit i: exp((3π/4) J_i).
    ///
    /// Equivalent to T^† (inverse of T).
    #[inline(always)]
    pub const fn three_quarter_turn_at(i: usize) -> Self {
        Self {
            q1_mask: 0,
            q2_mask: 0,
            q3_mask: 1u64 << i,
            sign: false,
        }
    }

    /// Alias: S gate on qubit i (same as J_i).
    #[inline(always)]
    pub const fn s_at(i: usize) -> Self {
        Self::j_at(i)
    }

    /// Alias: T gate on qubit i (same as quarter_turn_at).
    #[inline(always)]
    pub const fn t_at(i: usize) -> Self {
        Self::quarter_turn_at(i)
    }
}

// ============================================================================
// CLASS ARITHMETIC
// ============================================================================

impl Rotor {
    /// Construct a rotor from a local class (k mod 8) on qubit i.
    ///
    /// Automatically canonicalizes into one of the canonical classes {0, 1, 2, 3}
    /// with an optional global sign.
    ///
    /// # Class Table
    ///
    /// ```text
    /// k=0: identity (no bits, no sign)
    /// k=1: class 1 (q1 bit set)
    /// k=2: class 2 (q2 bit set)
    /// k=3: class 3 (q3 bit set)
    /// k=4: global negative sign only (equals -identity)
    /// k=5: class 1 with negative sign
    /// k=6: class 2 with negative sign
    /// k=7: class 3 with negative sign
    /// ```
    ///
    /// # Example
    /// ```
    /// let r = Rotor::class_at(0, 5);  // Qubit 0, class 5 = -class 1
    /// assert_eq!(r.q1_mask, 1);
    /// assert!(r.sign);  // Negative
    /// ```
    #[inline(always)]
    pub fn class_at(i: usize, k_mod_8: i8) -> Self {
        let mut k = k_mod_8 % 8;
        if k < 0 {
            k += 8;
        }

        let bit = 1u64 << i;

        match k {
            0 => Self::identity(),
            1 => Self {
                q1_mask: bit,
                q2_mask: 0,
                q3_mask: 0,
                sign: false,
            },
            2 => Self {
                q1_mask: 0,
                q2_mask: bit,
                q3_mask: 0,
                sign: false,
            },
            3 => Self {
                q1_mask: 0,
                q2_mask: 0,
                q3_mask: bit,
                sign: false,
            },
            4 => Self {
                q1_mask: 0,
                q2_mask: 0,
                q3_mask: 0,
                sign: true,
            },
            5 => Self {
                q1_mask: bit,
                q2_mask: 0,
                q3_mask: 0,
                sign: true,
            },
            6 => Self {
                q1_mask: 0,
                q2_mask: bit,
                q3_mask: 0,
                sign: true,
            },
            7 => Self {
                q1_mask: 0,
                q2_mask: 0,
                q3_mask: bit,
                sign: true,
            },
            _ => unreachable!(),
        }
    }

    /// Compute the multiplicative inverse of this rotor.
    ///
    /// For local class k, the inverse is class (-k) mod 8.
    /// Locally:
    /// - class 0 → class 0 (identity is self-inverse)
    /// - class 1 → class 7 (class 1 + sign)
    /// - class 2 → class 6 (class 2 + sign)
    /// - class 3 → class 5 (class 3 + sign)
    /// - sign → stays (global sign is self-inverse)
    ///
    /// The total sign correction accounts for parity of non-identity local classes.
    #[inline(always)]
    pub fn inverse(self) -> Self {
        let q1 = self.q1_mask;
        let q2 = self.q2_mask;
        let q3 = self.q3_mask;

        // Parity of total non-identity local classes
        let parity = ((q1.count_ones() + q2.count_ones() + q3.count_ones()) & 1) != 0;

        // Swap q1 <-> q3, keep q2, toggle sign based on parity
        Self {
            q1_mask: q3,
            q2_mask: q2,
            q3_mask: q1,
            sign: self.sign ^ parity,
        }
    }
}